
package br.com.Gui;

import br.com.ConexaoBanco.getConnection;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {

   String id, nome, telefone, rua, numero, cep, bairro, tipoPlano, DiaInicio, MesInicio, AnoInicio;
   String DiaFim, MesFim, AnoFim;
   boolean marcado = false;
   String lastId;
   
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        RadioCadastrar = new javax.swing.JRadioButton();
        lblTipoPlano = new javax.swing.JLabel();
        txtTipoPlano = new javax.swing.JTextField();
        lblInicioPlano = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtInicioDia = new javax.swing.JTextField();
        txtInicioMes = new javax.swing.JTextField();
        txtInicioAno = new javax.swing.JTextField();
        txtFimAno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFimMes = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFimDia = new javax.swing.JTextField();
        lblFimPlano = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblValor = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        btnEditar = new javax.swing.JToggleButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 728));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNome.setText("nome");

        lblTel.setText("telefone");

        lblRua.setText("rua");

        lblNumero.setText("numero");

        jLabel6.setText("cep");

        jLabel7.setText("bairro");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        RadioCadastrar.setText("Cadastrar plano:");
        RadioCadastrar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioCadastrarStateChanged(evt);
            }
        });
        RadioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCadastrarActionPerformed(evt);
            }
        });

        lblTipoPlano.setText("Plano");

        txtTipoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoPlanoActionPerformed(evt);
            }
        });

        lblInicioPlano.setText("Inicio do plano");

        jLabel10.setText("/");

        jLabel11.setText("/");

        txtInicioDia.setText("Dia");

        txtInicioMes.setText("Mes");

        txtInicioAno.setText("Ano");

        txtFimAno.setText("Ano");

        jLabel12.setText("/");

        txtFimMes.setText("Mes");

        jLabel13.setText("/");

        txtFimDia.setText("Dia");
        txtFimDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFimDiaActionPerformed(evt);
            }
        });

        lblFimPlano.setText("Fim do plano");

        btnCadastrar.setText("Cadastrar Novo Aluno");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Rua", "Numero", "Cep", "Bairro", "TipoPlano", "Valor", "InicioPlan", "FimPlan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblValor.setText("Valor");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar Registro");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRua)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtRua))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(lblValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtvalor)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTipoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTipoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(RadioCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInicioPlano)
                                    .addComponent(lblFimPlano))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txtFimDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFimMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFimAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInicioAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(650, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioCadastrar)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPlano)
                    .addComponent(txtTipoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInicioPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtInicioAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtFimDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFimMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtFimAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFimPlano))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnCadastrar)
                    .addComponent(btnDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(658, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        acaoRadioButton();
        ////
        
        
        
        mostrarDados();
        
    }//GEN-LAST:event_formWindowOpened

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
       
        Object nome = ""+jTable1.getValueAt(index, 1);
        Object telefone = ""+jTable1.getValueAt(index, 2);
        Object rua = ""+jTable1.getValueAt(index, 3);
        Object numero = ""+jTable1.getValueAt(index, 4);
        Object cep = ""+jTable1.getValueAt(index, 5);
        Object bairro = ""+jTable1.getValueAt(index, 6);
        Object tipoPlano = ""+jTable1.getValueAt(index, 7);
        Object valor = ""+jTable1.getValueAt(index, 8);
        Object inicioPlan = jTable1.getValueAt(index, 9);
        Object fimPlan = jTable1.getValueAt(index, 10);

        txtNome.setText(nome.toString());
        txtTel.setText(telefone.toString());
        txtRua.setText(rua.toString());
        txtNumero.setText(rua.toString());
        txtCep.setText(cep.toString());
        txtBairro.setText(bairro.toString());
        txtTipoPlano.setText(tipoPlano.toString());
        txtvalor.setText(valor.toString());

        //String textoSeparado1[] = inicioPlan.toString().split("-");
        
        if(inicioPlan != null){
        String textoSeparado1[] = inicioPlan.toString().split("-");
        txtInicioAno.setText(""+textoSeparado1[0]);
        txtInicioMes.setText(""+textoSeparado1[1]);
        txtInicioDia.setText(""+textoSeparado1[2]);
        }
        
        
        if(fimPlan != null){
        String textoSeparado2[] = fimPlan.toString().split("-");
        txtFimAno.setText(""+textoSeparado2[0]);
        txtFimMes.setText(""+textoSeparado2[1]);
        txtFimDia.setText(""+textoSeparado2[2]);
        }
            
        if(btnEditar.getText().equals("Salvar")){
            btnCadastrar.setEnabled(false);
            btnCadastrar.setVisible(false);
            System.out.println("" + txtNome.getText() + txtTel.getText());
           
        }
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //vars
        nome = txtNome.getText();
        telefone = txtTel.getText();
        rua = txtRua.getText();
        numero = txtNumero.getText();
        cep = txtCep.getText();
        bairro = txtBairro.getText();
        tipoPlano = txtTipoPlano.getText();
        DiaInicio = txtInicioDia.getText();
        MesInicio = txtInicioMes.getText();
        AnoInicio = txtInicioAno.getText();
        DiaFim = txtFimDia.getText();
        MesFim = txtFimMes.getText();
        AnoFim = txtFimAno.getText();

        getConnection c = new getConnection();
        String sql = "insert into pessoa values (default,?,?);";

        try {
            PreparedStatement stmt = c.conectarMysql().prepareStatement(sql);
            stmt.setString(1,nome);
            stmt.setString(2,telefone);
            stmt.execute();

            Statement stmt2;
            stmt2 = c.conectarMysql().createStatement();
            String sqlLast = "SELECT LAST_INSERT_ID() as id;";
            ResultSet rs = stmt.executeQuery(sqlLast);
            while (rs.next()) {
                lastId = rs.getString("id");
            }

            String sqlEnd = "insert into endereco (rua,numero,cep,bairro,pessoa_id_nome) values (?, ?, ?, ?, ?);";
            PreparedStatement stmtEnd = c.conectarMysql().prepareStatement(sqlEnd);
            stmtEnd.setString(1,rua);
            stmtEnd.setString(2,numero);
            stmtEnd.setString(3,cep);
            stmtEnd.setString(4,bairro);
            stmtEnd.setInt(5,Integer.parseInt(lastId));
            stmtEnd.execute();

            String sqlPlano = "insert into plano (tipo,valor,inicio,fim,pessoa_id_nome) values (?, ?, ?, ?, ?);";
            PreparedStatement stmtPlano = c.conectarMysql().prepareStatement(sqlPlano);
            if(RadioCadastrar.isSelected()){

                String dataInicio = AnoInicio+"/"+MesInicio+"/"+DiaInicio;
                String dataFim = AnoFim+"/"+MesFim+"/"+DiaFim;
                stmtPlano.setString(1,txtTipoPlano.getText());
                stmtPlano.setString(2,txtvalor.getText());
                stmtPlano.setString(3,dataInicio);
                stmtPlano.setString(4,dataFim);
                stmtPlano.setInt(5,Integer.parseInt(lastId));
                stmtPlano.execute();
            }

            stmt.close();
            stmt2.close();
            stmtEnd.close();;
            stmtPlano.close();

            mostrarDados();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtTipoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoPlanoActionPerformed

    private void RadioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCadastrarActionPerformed
        // TODO add your handling code here:
        acaoRadioButton();
    }//GEN-LAST:event_RadioCadastrarActionPerformed

    private void RadioCadastrarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioCadastrarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCadastrarStateChanged

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtFimDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFimDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFimDiaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        if(btnEditar.getText().equals("Salvar")){

            String sql = "UPDATE pessoa SET nome = ?, telefone = ? where id_nome = ?;";
            String sql2 = "update endereco set rua = ?, numero = ?, cep = ?, bairro = ?, pessoa_id_nome = ? where pessoa_id_nome = ?";
            String sql3 = "UPDATE pessoa SET nome = ?, telefone = ? where id_nome = ? ";
            try {
                 int index = jTable1.getSelectedRow();
                 Object id = ""+jTable1.getValueAt(index, 0);
                 
                PreparedStatement stmt = getConnection.conectarMysql().prepareStatement(sql);
                
                stmt.setString(1, txtNome.getText());
                stmt.setString(2, txtTel.getText());
                stmt.setInt(3, Integer.parseInt(id.toString()));
                stmt.execute();
                stmt.close();
                
                Object rua = jTable1.getValueAt(index, 3);
                Object numero = jTable1.getValueAt(index, 4);
                Object cep = jTable1.getValueAt(index, 5);
                Object bairro = jTable1.getValueAt(index, 6);
        
                if(rua == null && numero == null && cep == null && bairro == null){
                    
                    String sqlEnd = "insert into endereco (rua,numero,cep,bairro,pessoa_id_nome) values (?, ?, ?, ?, ?);";
                    PreparedStatement stmtEnd = getConnection.conectarMysql().prepareStatement(sqlEnd);
                    stmtEnd.setString(1,txtRua.getText());
                    stmtEnd.setString(2,txtNumero.getText());
                    stmtEnd.setString(3,txtCep.getText());
                    stmtEnd.setString(4,txtBairro.getText());
                    stmtEnd.setInt(5,Integer.parseInt(id.toString()));
                    stmtEnd.execute();
                    
                }else{
                    PreparedStatement stmt2 = getConnection.conectarMysql().prepareStatement(sql2);
                    stmt2.setString(1, txtRua.getText());
                    stmt2.setString(2, txtNumero.getText());
                    stmt2.setString(3, txtCep.getText());
                    stmt2.setString(4, txtBairro.getText());
                    stmt2.setInt(5, Integer.parseInt(id.toString()));
                    stmt2.setInt(6, Integer.parseInt(id.toString()));
                    stmt2.execute();
                    stmt2.close();
                }
                
                
             
                
                btnEditar.setText("Editar");
                btnCadastrar.setEnabled(true);
                btnCadastrar.setVisible(true);
                mostrarDados();
                
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            btnEditar.setText("Salvar");
            btnCadastrar.setEnabled(false);
            btnCadastrar.setVisible(false);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    
    public void acaoRadioButton (){
        if(RadioCadastrar.isSelected()){
            txtTipoPlano.setEnabled(true);
            txtInicioDia.setEnabled(true);
            txtInicioMes.setEnabled(true);
            txtInicioAno.setEnabled(true);
            txtFimDia.setEnabled(true);
            txtFimMes.setEnabled(true);
            txtFimAno.setEnabled(true);
            txtvalor.setEnabled(true);
        }else{
            txtTipoPlano.setEnabled(false);
            txtInicioDia.setEnabled(false);
            txtInicioMes.setEnabled(false);
            txtInicioAno.setEnabled(false);
            txtFimDia.setEnabled(false);
            txtFimMes.setEnabled(false);
            txtFimAno.setEnabled(false);
            txtvalor.setEnabled(false);
        }
        }
    
    public void mostrarDados(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
        model.setNumRows(0);
        
        Statement stmt;
        getConnection c = new getConnection();
        
        try {
            stmt = c.conectarMysql().createStatement();
            String sql = "select id_nome, nome, telefone, rua, numero, cep, bairro, tipo, valor, inicio, fim from pessoa left outer join endereco on endereco.pessoa_id_nome = pessoa.id_nome left outer join plano on pessoa.id_nome = plano.pessoa_id_nome order by pessoa.id_nome;";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                rs.getString("id_nome"),
                rs.getString("nome"),
                rs.getString("telefone"),
                rs.getString("rua"),
                rs.getString("numero"),
                rs.getString("cep"),
                rs.getString("bairro"),
                rs.getString("tipo"),
                rs.getString("valor"),
                rs.getString("inicio"),
                rs.getString("fim")});
                 

            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioCadastrar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFimPlano;
    private javax.swing.JLabel lblInicioPlano;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTipoPlano;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtFimAno;
    private javax.swing.JTextField txtFimDia;
    private javax.swing.JTextField txtFimMes;
    private javax.swing.JTextField txtInicioAno;
    private javax.swing.JTextField txtInicioDia;
    private javax.swing.JTextField txtInicioMes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTipoPlano;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables

}
